---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: fabric8-maven-sample-zero-config
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: fabric8-maven-sample-zero-config@sha256:df0c8a857c3439b140810e7cc77d96796918734b262c79d7145799c97030f8e3
        namespace: myproject
      name: latest
